# This workflow updates the Recent Activity section in your README.md using the Readme-Workflows/recent-activity GitHub Action
# It runs every 12 hours and can also be triggered manually
name: Update Recent Activity in README

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: ShlokBajaj3433
